name: e64.us
markdown: redcarpet
highlighter: pygments # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]
baseurl: "" # should not begin or end with /
relative_permalinks: false
destination: '_site'
includes:
  - images
